In [1]:
array = [1,2,3,4,5,6]

In [3]:
import numpy as np

In [74]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
type(arr2d)

numpy.ndarray

In [76]:
arr2d[:1]
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2, 2:]

array([[3],
       [6]])

In [59]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [48]:
arr2d[:2, 1:] = 0

In [52]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 9]])

In [51]:
arr2d[2,1] = 0

In [53]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 9]])

#### Boolean Indexing

In [93]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
data

array([[-0.46868939,  0.65397762,  0.97387859, -0.24592806],
       [-1.11160959, -1.64952218,  1.15403406, -0.93168534],
       [ 0.22985117,  1.19499751, -0.25852642, -1.00987557],
       [-0.73516162,  1.09211167,  0.86717552,  2.33270805],
       [-0.30859645, -1.83938117, -0.6113523 , -0.19172998],
       [-1.27843473, -1.22729412, -0.0876146 , -1.96646949],
       [-0.13264052,  0.98396157,  1.79687135,  0.98678263]])

In [81]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [83]:
data[names == 'Bob', 2:]

array([[ 0.97387859, -0.24592806],
       [ 0.86717552,  2.33270805]])

In [84]:
data[names == 'Will', :2]

array([[ 0.22985117,  1.19499751],
       [-0.30859645, -1.83938117]])

In [85]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [86]:
data[~(names == 'Bob')]

array([[-1.11160959, -1.64952218,  1.15403406, -0.93168534],
       [ 0.22985117,  1.19499751, -0.25852642, -1.00987557],
       [-0.30859645, -1.83938117, -0.6113523 , -0.19172998],
       [-1.27843473, -1.22729412, -0.0876146 , -1.96646949],
       [-0.13264052,  0.98396157,  1.79687135,  0.98678263]])

In [89]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [90]:
data[mask]

array([[-0.46868939,  0.65397762,  0.97387859, -0.24592806],
       [ 0.22985117,  1.19499751, -0.25852642, -1.00987557],
       [-0.73516162,  1.09211167,  0.86717552,  2.33270805],
       [-0.30859645, -1.83938117, -0.6113523 , -0.19172998]])

In [92]:
data[data < 0] = 10
data

array([[10.        ,  0.65397762,  0.97387859, 10.        ],
       [10.        , 10.        ,  1.15403406, 10.        ],
       [ 0.22985117,  1.19499751, 10.        , 10.        ],
       [10.        ,  1.09211167,  0.86717552,  2.33270805],
       [10.        , 10.        , 10.        , 10.        ],
       [10.        , 10.        , 10.        , 10.        ],
       [10.        ,  0.98396157,  1.79687135,  0.98678263]])

In [100]:
data[names == 'Will'] = 3
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.44172061, -0.01354065, -0.46962318, -0.81462496],
       [ 3.        ,  3.        ,  3.        ,  3.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 3.        ,  3.        ,  3.        ,  3.        ],
       [-2.42514934,  1.64727896,  1.56005722, -1.53306812],
       [-0.10643896,  0.5392426 , -1.04970103, -0.38602269]])

In [97]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-1.44172061, -0.01354065, -0.46962318, -0.81462496],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-2.42514934,  1.64727896,  1.56005722, -1.53306812],
       [-0.10643896,  0.5392426 , -1.04970103, -0.38602269]])

### **** LAB SESSION ****

#### Array Functions

In [1]:
data1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr2 = np.asarray(data1)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones_like(data1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
np.zeros(1)

array([0.])

In [28]:
new = np.empty(3)
new

array([1.33508845e-306, 1.33511969e-306, 9.34593493e-307])

In [31]:
new1 = np.full()

TypeError: full() missing 1 required positional argument: 'fill_value'

In [2]:
import numpy as np

In [3]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i